kind: pipeline
type: ssh
name: drone-test

clone:
  disable: true

server:
  host: 172.31.15.235
  user: abi-test
  password: password

steps:
- name: greeting
  commands:
  - echo halo
  - cd /home/abi-test
  - mkdir test-drone
