kind: pipeline
type: ssh
name: drone-test

clone:
  disable: true

server:
  host:
    from_secret: myHost
  user:
    from_secret: myUser
  password: 
    from_secret: myPassword

steps:
- name: greeting
  commands:
  - echo halo from master
