kind: pipeline
type: ssh
name: drone-test

clone:
  disable: true

server:
  host:
    from_secret: myHost
  user:
    from_secret: myUser
  password: 
    from_secret: myPassword

steps:
- name: greeting
  commands:
  - echo halo from master
  - echo hai dari master

---
kind: pipeline
type: docker
name: notify-test

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook: 
      from_secret: mySlackWebhookTest
    channel: devops-division
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

