kind: pipeline
type: ssh
name: drone-test

clone:
  disable: true

server:
  host:
    from_secret: myHost
  user:
    from_secret: myUser
  password: 
    from_secret: myPassword

steps:
- name: greeting
  commands:
  - echo halo from master
  - echo hai dari master

---
kind: pipeline
type: docker
name: notify-test

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook: 
      from_secret: mySlackWebhookTest
    channel: devops-division
    image_url: https://picsum.photos/id/180/256/256
    template: >
      {{#success build.status}}
       Build: {{build.number}} 
       Project: {{repo.name}} 
       Branch: {{build.branch}} 
       Status: {{build.status}}
       Link: {{build.link}}
       Author: {{build.author}}
       Good Job :)
      {{else}}
       Build: {{build.number}} 
       Project: {{repo.name}} 
       Branch: {{build.branch}} 
       Status: {{build.status}}
       Link: {{build.link}}
       Author: {{build.author}}
       Fix me please :(
      {{/success}}

